---
- block:
    - name: Retrieve proxy container ip
      include_tasks: /etc/ansible/task/app/proxy/container/property/ip.yml
    - name: Up monitor container
      include_role:
        name: app/monitor/container/up
      vars:
        _env: '{{ env }}'
        _compose_project_name: '{{ namespace }}monitor'
        _network: '{{ namespace }}proxy_default'
        _proxy_host: '{{ proxy_container_ip.stdout }}'
        _ui_host: '{{ app.monitor.ui.host }}'
        _directory: '{{ directory }}/monitor'
  when: app.monitor.enabled
  tags: [monitor]
